all:
  hosts:
    demo:
      ansible_host: 31.97.45.223     # IP deines VPS
      ansible_user: root             # oder ein sudo-User
      leihs_external_hostname: demo.meine-domain.tld
      leihs_send_mails: "No"         # bis Mail-Relay eingerichtet ist
      db_backup_on_deploy: "No"
      db_backup_nigthly_enabled: "No"

leihs_server:
  hosts:
    demo:
